pingcap/badger

db.go
levels.go
manifest_test.go
skl/arena.go
skl/skl.go
table/builder.go
table/iterator.go
table/table.go
table/table_test.go
value.go
y/iterator.go

1. store block base keys together at the end of a table, avoid heavy random I/O during loading, speed up loading time.
2. refactor blockIterator to utilize the entry index and simplify code.
3. replace *bytes.Buffer with []byte, and set initial capacity.
4. unsafely convert []uint32 to []byte to avoid memory allocation.
5. add keys to bloom filter directly to avoid memory copy.
6. replace some AssertTruef to AssertTrue.

add base keys in the end of a table and more optimizations

---

iterator.go
y/iterator.go
y/iterator_test.go

The microbenchmark shows that the new merge iterator improved the performance
from
`20694 ns/op`
to
`8509   ns/op`
on merging 2 chilren iterators.
from
`176898 ns/op` 
to 
`134595 ns/op` 
on merging 8 children iterators.

optimize merge iterator

---

iterator.go
y/iterator.go

Iterate over 2 million sysbench keys, 1 million row and 1 million indices.
Before: 600ms
After: 420ms
Iterate writeCF in RocksDB takes 320ms.
So still 30% slower than RocksDB, but much better.

optimize MergeIterator

---

db.go
writer.go

Split `writeRequests` into `writeVLog` and `writeLSM`, runs in different goroutines.
Reduce blocking latency.

refactor writer

---

skl/skl.go
skl/skl_test.go

Under 64MB table size, sequentially put 1M keys takes less than 100ms, 4x improvement compares to no hint Put.

support PutWithHint, speed up sequential write

---

db.go
level_handler.go
levels.go
manifest_test.go
options.go
options/options.go
table/builder.go
table/hash_index.go
table/iterator.go
table/table.go
table/table_test.go

Likes [RocksDB's block hash index](https://rocksdb.org/blog/2018/08/23/data-block-hash-index.html). Can improve point get performance.
Result of BenchmarkPointGet
~~BenchmarkPointGet/Seek-12                  10000           2890639 ns/op
BenchmarkPointGet/Hash-12                  10000           2142101 ns/op~~
~~BenchmarkPointGet/Seek-12                  10000           2839140 ns/op
BenchmarkPointGet/Hash-12                  10000           2316540 ns/op~~
~~BenchmarkPointGet/Seek-12                  10000           2856267 ns/op
BenchmarkPointGet/Hash-12                  10000           2529225 ns/op~~

Add block hash index to sst file

---

db.go
fileutil/file_writer.go
fileutil/preallocate.go
fileutil/preallocate_linux.go
fileutil/preallocate_others.go
fileutil/sync.go
fileutil/sync_darwin.go
fileutil/sync_linux.go
levels.go
manifest_test.go
options.go
options/options.go
structs.go
table/builder.go
table/hash_index.go
table/table_test.go
value.go
value_test.go

There are some shortcomings in badger’s IO related part.
* Use `O_DSYNC` instead of `fdatasync`, besides some platform define `O_DSYNC` but doesn’t respect to it (fortunately Linux 3.2.0+ works well), this flag also restrict the way we write data to file. Because each `write` call will sync data, so we must keep as much as possible data in buffer instead of let it in system cache.
* Unfortunately, due to badger doesn’t preallocate file with desired size, each `write` will extend file size. In this case, `fdatasync (O_DSYNC)` have to update file’s metadata.
* To control the IO spike, currently we break table flush to small chunks and write them chuck by chunk. But according to previous reason, it cause a lots of metadata update. As final result, the flushing process takes a longer time to …

refactor io related part in table builder

---

fileutil/file_writer.go
fileutil/sync.go
fileutil/sync_darwin.go
fileutil/sync_linux.go
level_handler.go
table/mem_table.go

* let `sync_file_range` block until disk IO done. Let write slow down when the disk is busy.
* fix two crash bugs.

fix crash and sync_file_range refine

---

level_handler.go
levels.go
options.go
table/iterator.go
table/table.go

Use sub compaction to avoid write stall due to large L1 to L2 compaction block L0 compaction, and speed up L0 to L1 compaction.

support sub compaction to speed up large compaction

---

db_test.go
levels.go
options.go

This compaction filter is a stateless function, it doesn't support rewrite value.
It's simpler than the rocksDB's one but sufficient to support GC in unistore.

support compaction filter

---

levels.go
manifest_test.go
options.go

* remove `NumVersionsToKeep`
* delete tombstone when there is no overlapped lower level.
* simplify `compactBuildTables`

optimize key discrading in compactBuildTables

---

table/iterator.go

Makes iterator struct smaller, reduce allocation cost.

remove keyBuf in table iterator

---

transaction.go
transaction_test.go

`MultiGet` doesn't check whether a key is deleted. 
PTAL @coocood

fix MultiGet

---

db.go
db_test.go
levels.go
transaction.go
y/wartermark_test.go
y/watermark.go

It makes new transaction much cheaper.
Benchmark result:
BenchmarkFastWaterMark-8   	10000000	       158 ns/op	      32 B/op	       1 allocs/op
BenchmarkWaterMark-8       	 1000000	      1177 ns/op	      16 B/op	       1 allocs/op

implement FastWaterMark

---

db.go
db_test.go
iterator.go
level_handler.go
levels.go
transaction.go
value.go

- Use RefMap to store referenced table, DecrRef at txn Discard.
- Use y.CompareKeys instead of bytes.Compare

fix MultiGet bugs

---

levels.go

Access of `tables` and `totalSize` in `cd.thisLevel` should protected by `cd.thisLevel.RLock()`.
For performance considerations, doesn't access these fields when logging.

fix race in doCompact

---

db.go
levels.go
y/metrics.go

add some metrics for compaction

---

db_test.go
fileutil/sync.go
fileutil/sync_darwin.go
fileutil/sync_linux.go

We don’t need to wait for the buffer on the storage device to flush on macOS.
Enlarge the mem table size in test option to speed up the unit test.

use syscall.Fsync for darwin platform.

---

level_handler.go
levels.go

If all top tables doesn’t contain a bottom table’s range, we can skip the bottom table in the compaction.
Reduces write amplification.

compaction skip non-overlapping bottom tables

---

levels.go

`getKeyRange` ignored skipped tables, so compaction jobs may modify the same table concurrently.
PTAL @coocood

fix incorrect compaction status check

---

backup_test.go
db.go
db_test.go
manifest_test.go
table/merge_iterator.go
table/merge_iterator_test.go
value.go
writer.go

* Fix incorrect result of `MergeIterator`
* Fix segment fault caused by `MemTable`
* Fix memory leak in tests
* Fix random fail on GC related tests (port changes in `doRunGC` from upstream)

fix some bugs

---

compaction.go
db.go
level_handler.go
levels.go
manifest.go
manifest_test.go
protos/backup.pb.go
protos/manifest.pb.go
protos/manifest.proto
table/builder.go
table/iterator.go
table/table.go
value_test.go
writer_ingest.go

- Move the information in the head key to the manefest, reduce compaction cost.
- Fix bug that the smallest key in the table is not the smallest.
- Fix bug in `levelHandler.replaceTables`, should not return when `len(newTables) == 0`.

remove head key and fix bug of table.Smallest()

---

blob.go
iterator.go
transaction.go

Sysbench 30 million rows. `select count(c) from sbtest1` improved from 55 seconds to 0.85 seconds.

support blob read ahead cache

---

surf/bits_vec.go
surf/bits_vec_test.go

`labelVector` stores the children's labels for `LOUDS Sparse` format.
If the `LOUDS Sparse` contains `key`, `key1` and `key2`, the 4th level node's `lavelVector` will be `[labelTerminator, 1, 2]`. The first `labelTerminator` means the current node path is a valid key.
PTAL @coocood

add label vector of SuRF

---

db.go
levels.go
manifest_test.go
table/builder.go
table/hash_index.go
table/table.go
table/table_test.go

Use `.idx` file to store data of index. Also add some required meta into index file, so that `OpenTable` doesn't need to load block data.
PTAL @coocood

split index and block data

---

skl/skl.go
skl/skl_test.go
table/merge_iterator.go

```
BenchmarkGetSequential-12                3572689               341 ns/op
BenchmarkGetWithHintSequential-12       10696102               116 ns/op
BenchmarkGetRandom-12                    1213249               967 ns/op
BenchmarkGetWithHintRandom-12            1000000              1123 ns/op
```

support GetWithHint

---

table/iterator.go

If `tbl.HasGlobalKey()`, the `itr.bi.key` has append this ts to the key.

return the correct raw key if sst has global ts

---

blob_test.go
db.go
db_test.go
options.go
table/table.go
transaction.go
transaction_test.go
writer.go

So we can set the table file to be much smaller to reduce compaction cost.

Use different option for max mem-table size and max table-file size.

---

db.go
iterator.go
level_handler.go
levels.go
managed_db.go
options.go
structs.go
transaction.go
transaction_test.go
value.go

- Support hidden entry which can only be visible if ReadHidden is set.
- Support SetReadTS to update ReadTS for a transaction.
- Support UpdateSafeTS for GC old version on managed DB.

Managed DB support set commit version for each entry.

---

cache/cache.go
cache/cache_test.go
cache/store.go
table/table.go

Use `GetOrCompute` to prevent loading the same block multiple times when access them concurrently.
PTAL @coocood

cache: support GetOrCompute

---

blob.go
db.go
epoch/manager.go
manifest_test.go
options.go
writer.go

Fix goroutine leak in TiDB's unit tests.
Provide a `VolatileMode` to reduce the disk usages when use it in TiDB's unit tests.

add volatile mode and close background workers

---

table/sstable/builder.go
table/sstable/iterator.go
table/sstable/table.go
table/sstable/table_test.go

This reverts commit 0244807ae70df8956661ca4cc7df3d68078e3eea.
The implementation has some bug cause panic.
And it's not suited for clustered index feature because the row key diff may vary a lot.

Revert "support seek by uint64 in SST (#196)"

---

dir_windows.go

The file lock implementation on win32 platform is incorrect, the lock cannot be released after the process is killed.
The `windows.CreateFile` doesn't handle win32 errors correctly, so I have to use my own wrapper.

fix badger cannot start after KILL on Windows

---

blob_test.go
compaction.go
db.go
db_test.go
levels.go
manifest_test.go
options.go
options/options.go
table/sstable/builder.go
table/sstable/table.go
table/sstable/table_test.go
transaction_test.go

So remote compaction doesn't need to read and write files.

support build and open in-memory SST

---

db.go
db_test.go
iterator.go
levels.go
options/options.go
table/concat_iterator.go
table/memtable/skl.go
table/memtable/skl_test.go
table/memtable/table.go
table/memtable/table_test.go
table/merge_iterator.go
table/merge_iterator_test.go
table/sstable/iterator.go
table/sstable/table.go
table/sstable/table_test.go
transaction.go
value_test.go
writer_ingest.go
y/iterator.go

Key:10
Value:1024
Batch:1024
Total entries:10000*1024
|Package|dgraph-io|pingcap|changed|
|:--:|:--|:--|:--|
|Total alloc|172.34GB|34.81GB|31.98GB|
|Block alloc|105.91GB|2.33GB|0.82GB|
Total Entries:4096*1024
|Package|dgraph-io|pingcap|changed|
|:--:|:--|:--|:--|
|Total alloc|32.54GB|2.20GB|2.21GB|
|Block alloc|16.43GB|0.27GB|0.28GB|
Key:512
Value:512
Batch:1024
Total Entries:10000*1024
|Package|dgraph-io|pingcap|changed|
|:--:|:--|:--|:--|
|Total alloc|220.48GB|84.74GB|40.51GB|
|Block alloc|89.33GB|44.92GB|3.56GB|
Total Entries:4096*1024
|Package|dgraph-io|pingcap|changed|
|:--:|:--|:--|:--|
|Total alloc|33.90GB|66.99GB|6.69GB|
|Block alloc|17.32GB|60.10GB|1.06GB|
debug/pprof/goroutine
```
#	0x106c626	sync.runtime_SemacquireMutex+0x46				/usr/local/go/src/runtime/sema.go:71
#	0x107b8c4 …
```

Reuse buffer and fix a deadlock in levelsController

---

cache/z/z.go
go.mod
go.sum

Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
fix the error when to build in golang 1.18
```
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/go/pkg/mod/github.com/cespare/xxhash@v1.1.0/xxhash_amd64.s:120)	ADDQ	R15, AX
```

update xxhash for golang1.18

---

blob.go
db.go
db_test.go
directio/proxy.go
fileutil/writer.go
fileutil/writer_test.go
levels.go

Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
If the file system doesn't support directio, just let it go without O_DIRECT. The most common case where direct io is not supported is the tmpfs, and it brings some pain for test.

open with directio at best effort

---

directio/proxy_linux.go
directio/proxy_other.go

Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
The directio pkg uses `unix.EINVAL`, which doesn't exit in windows. To support windows, I'd add a compilation flag and use the original directio directly.
I also find that the errors returned in the darwin and openbsd is different with Linux. In Linux, it returns the return the EINVAL (directly by the system call). For darwin, it's a software defined "Failed to set F_NOCACHE: %s". The windows seems to be more complicated. As I don't have a Mac OS / Windows device, I left it here to return the result directly.  
Actually, I'm not sure whether there are file systems like tmpfs which don't support direct io in Mac OS and other systems.

fix windows compile error for directio pkg
