pingcap/badger

- db.go
- db_test.go
- errors.go
- iterator.go
- options.go
- transaction.go
- value.go
- value_test.go
> remove value log mmap option

- table/iterator.go
Currently, table iterator returns a value that is a reference to mmap, it's only safe to use until the iterator Close.
But in the `txn.Get` operation, the iterator is closed after the function return, so we need to make a copy to the referenced memory.
> fix segment fault.

- level_handler.go
- table/iterator.go
The memory copy is introduced by https://github.com/coocood/badger/pull/15
> avoid value copy introduced by previous commit

- db.go
- levels.go
> write to file step by step

- iterator.go
The iterator does an extra Next, so without SafeCopy, the item key and value can be invalid.
Extract forward non-prefetch iteration to its own function to improve the performance and avoid the copy.
Iterate 2million keys improved from 240ms to 180ms.
> fix iterator bug and further optimize

- iterator.go
- transaction.go
- transaction_test.go
This reverts commit 9bf04b06cf75b775a9ff8202fc24bef067eaaaa4.
> Revert "do not track conflict inside transactions"

- skl/skl.go
We walk on the higher level until we found a key greater than target key, then go to the lower level.
There is 1/3 chance we will compare the same node at the upper level. since we already know it is greater than the target key, we don't need to compare again.
After this optimization, when the skiplist size is 1MB, the improvement is about 5%, but when the size is larger like 64MB, the improvement is only 2%
May be that's because the key is already in L1 cache when we compare it again.
> avoid unnecessary compare

- skl/skl_test.go
- table/builder.go
- table/iterator.go
remove a falke test
rename two fields
clean up unnecessary assignments
> Tiny refactor

- backup.go
- backup_test.go
- db_test.go
- errors.go
- iterator.go
- manifest_test.go
- skl/skl_test.go
- structs.go
- table/merge_iterator_test.go
- table/table_test.go
- transaction.go
- value.go
- y/iterator.go
According to discussion in #60, change `UserMeta` to `[]byte`
> change UserMeta to []byte

- compaction.go
- fileutil/file_writer.go
- levels.go
- value.go
- y/metrics.go
Add an atomic counter to track writing file interface.
> refactor: keeping variables's name more consistent

- value.go
> fix vlog replay

- table/iterator.go
copy less data in `blockIterator.setIdx`
> tiny optimization

- fileutil/file_writer.go
- value.go
- writer.go
Use a separate thread to call fdatasync, let WALWriter computes checksum and write data to OS page cache.
PTAL @coocood
> use a separate thread to sync data

- db.go
- level_handler.go
- levels.go
- manifest_test.go
- options.go
- options/options.go
- table/builder.go
- table/table_test.go
- y/metrics.go
Changes:
* Calculate the optimal FPR for bloom filter in `Builder.Finish`
* Add & update some metrics
> using the optimal bloom filter size suggested by monkey

- levels.go
> clear bottom tables list when fill tables fails

- levels.go
> fix bug in fillTables

- table/builder.go
- table/iterator.go
- table/table.go
- table/table_test.go
Add a `global ts` in SST format. So SST ingest can be done with these steps:
1. Build SST outside badger with builder created by `NewExternalBuilder`. The keys added have no timestamp appended
2. Call `IngestSST` (will support in next PR)
3. Inside `IngestSST` badger will allocate a proper timestamp for all keys in SST and update table using `SetGlobalTs`
PTAL @coocood
> add external table ts support

- db.go
- db_test.go
- level_handler.go
- levels.go
- table/iterator.go
- table/table.go
- transaction.go
- writer.go
- writer_ingest.go
basic support of sst ingestion.
PTAL @coocood
> support sst ingest

- db_test.go
- iterator.go
- table/merge_iterator_test.go
- transaction.go
- transaction_test.go
- value.go
- value_test.go
Prepare for change value-log to WAL, separate values from keys during compaction.
> remove prefetch feature, simplify code logic

- db.go
* Bug fix;
* Sort external files before check;
* Add `DB.NewTableBuilder`, reuse db's opts.
> refine sst ingest

- blob.go
- blob_test.go
- db.go
- fileutil/writer.go
- iterator.go
- levels.go
- options.go
- table/table.go
- transaction.go
blob GC is run automatically and doesn't need to access the LSM tree.
Set ValueThreshold to 0 to store all values in the LSM tree.
> support blob file, separate keys and values.

- blob.go
- blob_test.go
- db.go
- fileutil/writer.go
- manifest_test.go
- fix file id conflict by using a separated file id allocator
- fix incorrect file size
- fix build logical to physical map from ChangeLog
- open and close DB multiple times in test
> fix blob bugs

- skl/arena.go
- skl/skl.go
- skl/skl_test.go
- y/iterator.go
> change ValueStruct size type from uint16 to uint32

- go.mod
- go.sum
- surf/bits.go
- surf/bits_amd64.go
- surf/bits_amd64.s
- surf/bits_others.go
- surf/bits_vec.go
- surf/bits_vec_test.go
> add basic bits util and bits vector of SuRF

- surf/bits_vec.go
`suffixVector` contains the suffix part of `SuRF`.
> add suffixVector

- surf/bits_vec.go
`prefixVector` used by prefix compression to store the compressed node's labels (prefix).
> add prefixVector

- surf/louds_dense.go
- surf/louds_sparse.go
- surf/surf.go
The missing `LOUDS` building function will added with SuRF builder.
> add point get of SuRF

- surf/bits_vec.go
- surf/louds_dense.go
- surf/louds_sparse.go
- surf/surf.go
- surf/surf_test.go
Also fix some bug found during test. More test will be added in next PR.
> add SuRF Iterator and basic tests for it

- go.mod
- go.sum
- surf/bits_vec.go
- surf/louds_sparse.go
- surf/surf_test.go
> add more test about iterator and fix bugs

- db_test.go
- fileutil/writer.go
- iterator.go
- level_handler.go
- levels.go
- options.go
- options/options.go
- table/builder.go
- table/hash_index.go
- table/iterator.go
- table/table.go
- table/table_test.go
- writer_ingest.go
Can config strat from which level use SuRF to replace bloom + hash.
> add surf support in SST

- blob.go
Fixes https://github.com/coocood/badger/issues/146
> fix blob id allocation for GCed blob file

- db.go
- db_test.go
- structs.go
- table/mem_table.go
- transaction.go
- value.go
- value_test.go
- writer.go
> remove txn size limit

- backup_test.go
- db.go
- go.mod
- go.sum
- levels.go
- manifest_test.go
- options.go
- table/table.go
- table/table_test.go
> port block cache

- db.go
- table/table.go
The block cache has some performance issues, so before we have fully optimized it we can set `MaxCacheSize = 0` to use the old `mmap` way.
PTAL @coocood
> allow disable block cache and use mmap to access sst

- db.go
- db_test.go
- level_handler.go
- levels.go
Port https://github.com/dgraph-io/badger/pull/1186
> Do not stall Level 1

- writer.go
When flusher is run, the the flusher sends messages to writeLSMch,
So we should let the flusher close this channel when close.
> fix send on closed channel

- compaction.go
- db.go
- level_handler.go
- levels.go
- manifest_test.go
- writer_ingest.go
Pick the max topSize/bottomSize ratio table to compact.
> improve compaction pick table strategy

- cmd/badger/cmd/info.go
- compaction.go
- db.go
- db_test.go
- iterator.go
- level_handler.go
- levels.go
- skl/arena.go
- skl/skl.go
- skl/skl_test.go
- structs.go
- table/builder.go
- table/iterator.go
- table/mem_table.go
- table/merge_iterator.go
- table/merge_iterator_test.go
- table/table.go
- table/table_test.go
- transaction.go
- transaction_test.go
- util.go
- value.go
- value_test.go
- writer.go
- writer_ingest.go
- y/iterator.go
- y/y.go
So we never confuse the key with or without version.
> refactor the key type

- db_test.go
- table/builder.go
- table/iterator.go
- transaction_test.go
In the prev PR https://github.com/coocood/badger/pull/173
The base key was changed to doesn't contain the version. which caused read incorrect results from the table.
> fix build table bug introduced by key refactor.

- db.go
- iterator.go
- level_handler.go
- levels.go
- structs.go
- table/iterator.go
- transaction.go
- transaction_test.go
- value.go
This feature makes GC complex in Unistore.
> remove Hidden feature

- value.go
- value_test.go
Should not break when FinTxn ts is not equal to txn ts for managed DB
> fix log replay for managed DB

- cache/cache.go
- db.go
- level_handler.go
- levels.go
- manifest_test.go
- options.go
- table/builder.go
- table/iterator.go
- table/table.go
- table/table_test.go
1. Add index cache, this requires us to change the way to access index fields.
2. Update the the cache configs, the old config waste some memory.
3. Add a little error handling in read path, need more works here in the future.
> add cache support for index data

- blob.go
For better random read performance.
> make blob cache size smaller

- levels.go
Don't need to wait for 3 seconds for compactor to quit if db has been closed.
> make DB.Close faster

- levels.go
Makes badger faster to open and close.
> do not sleep before run compaction worker

- cache/cache_test.go
- db.go
- table/memtable/arena.go
- table/memtable/skl.go
- table/memtable/skl_test.go
- table/memtable/table.go
- table/sstable/builder.go
- table/sstable/iterator.go
- table/sstable/table_test.go
- transaction_test.go
- writer.go
- y/iterator.go
- y/y.go
So we can later skip old versions when iterate.
> store old version entries of a same key in a linked list in SkipList

- db.go
- iterator.go
- levels.go
- table/concat_iterator.go
- table/memtable/skl.go
- table/memtable/skl_test.go
- table/memtable/table.go
- table/memtable/table_test.go
- table/merge_iterator.go
- table/merge_iterator_test.go
- table/sstable/iterator.go
- table/sstable/table.go
- table/sstable/table_test.go
- transaction.go
- transaction_test.go
- writer_ingest.go
- y/iterator.go
- Next only returns the latest version
- NextVersion returns the next older version.
> change y.Iterator interface to skip old versions.

- table/sstable/builder.go
- table/sstable/iterator.go
- table/sstable/table.go
- table/sstable/table_test.go
Improves the Seek performance on SST.
Before:
BenchmarkRandomRead-12	1247887	897 ns/op
After:
BenchmarkRandomRead-12	2784578	436 ns/op
> support seek by uint64 in SST

- db.go
Save memory usage and improve performance for non-exist get.
> remove fastL0Table optimization

- table/sstable/iterator.go
- table/sstable/table_test.go
has old version is not reset after call next.
> fix sst iterator

- cache/cache.go
- cache/policy.go
add `SetNewMaxCost` function in `cache` to modify `maxCost` after create the cache.
> add setNewMaxCost

- cache/cache.go
- cache/store.go
> update clear() function and make it safer.

- s3util/s3util.go
- s3util/scheduler.go
- shard_compact.go
- shard_ingest.go
https://github.com/ngaut/unistore/issues/451
* fix a decode fid bug
* add a batch load scheduler
> load S3 files in parallel

- shard_db.go
To view shard db info, open http://status-addr/debug/db in your browser.
```
Time 2021-05-10T20:29:19.091294+08:00
Manifest.shards 15
Manifest.globalFiles 4
MemTables 15, MemTablesSize 1,150,218
L0Tables 4, L0TablesSize 329,694
CFs 45, Levels 180, CFsSize 0
ShardMap 15
Shard ID 2, Version 5, SplitState INITIAL
MemTables 1
MemTable 0, Size 474, Empty true 
L0Tables 0
cfs 3
CF 0, levels 4 
LevelHandler 0, level 1, tables 0, totalSize 0 
LevelHandler 1, level 2, tables 0, totalSize 0 
LevelHandler 2, level 3, tables 0, totalSize 0 
LevelHandler 3, level 4, tables 0, totalSize 0 
CF 1, levels 4 
LevelHandler 0, level 1, tables 0, totalSize 0 
LevelHandler 1, level 2, tables 0, totalSize 0 
LevelHandler 2, level 3, tables 0, totalSize 0 
LevelHandler 3, level 4, tables 0, totalSize 0 
CF 2, …
```
> add debug handler to shard db 

- db.go
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>
close #220
> db.go: close indexCache in (*DB).Close()
